---
- name: Update apt repositories
  become: true
  ansible.builtin.apt:
    upgrade: "full"
    update_cache: true

- name: Install packages required by Kubernetes
  become: true
  ansible.builtin.apt:    
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Download the public signing key for the Kubernetes package repositories
  become: true
  ansible.builtin.shell:
    cmd: |
      if [ ! -f "/etc/apt/keyrings/kubernetes-apt-keyring.gpg" ]; then curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg; fi


- name: Add the appropriate Kubernetes apt repository
  become: true
  ansible.builtin.shell:
    cmd: |
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt repositories
  become: true
  ansible.builtin.apt:
    upgrade: "full"
    update_cache: yes
    
- name: Install Kubernetes packages
  become: true
  ansible.builtin.apt:
    name: 
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Pin kubeadm version
  become: true
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
  
- name: Pin kubelet version
  become: true
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold
  
- name: Pin kubectl version
  become: true
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold